[package]
name          = "tikhonov"
version       = { workspace = true }
edition       = { workspace = true }
rust-version  = { workspace = true }
license       = { workspace = true }
repository    = { workspace = true }
authors       = { workspace = true }
description   = "Harmony2 single-cell data integration"
keywords      = ["bioinformatics", "single-cell", "harmony", "integration"]
categories    = ["science"]

[lib]
name       = "tikhonov"
crate-type = ["rlib"]

[dependencies]
